apiVersion: v1
kind: Namespace
metadata:
  name: dedicated
---

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-dedicated
  namespace: dedicated

spec:
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
