apiVersion: v1
kind: Namespace
metadata:
  name: loaded

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: unloaded

---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-loaded
  namespace: loaded
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-unloaded
  namespace: unloaded
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
